Repository tensorflow/runtime, pull requests merged in 2021-08, with the labels that each got.

#76 bef_name is no longer used and can be safely removed
  backends/common/mlir_tests/compat/eigen/BUILD
  backends/cpu/mlir_tests/core_runtime/BUILD
  backends/cpu/mlir_tests/jit/BUILD
  backends/cpu/mlir_tests/mnist/BUILD
  backends/cpu/mlir_tests/resnet/BUILD
  backends/cpu/mlir_tests/tf_kernels/BUILD
  backends/gpu/mlir_tests/core_runtime/BUILD
  backends/gpu/mlir_tests/cuda/BUILD
  integrationtest/fizzbuzz/BUILD
  integrationtest/mnist/BUILD
  integrationtest/resnet/BUILD
  mlir_tests/basic_kernels/BUILD
  mlir_tests/bef_executor/BUILD
  mlir_tests/bef_to_mlir/BUILD
  mlir_tests/code_size_test_app/BUILD
  mlir_tests/compiler/BUILD
  mlir_tests/core_runtime/BUILD
  mlir_tests/lit.cfg.py
  mlir_tests/mlir_to_bef/BUILD
  mlir_tests/tensor/BUILD
  mlir_tests/tracing/BUILD
  tools/BUILD
  tools/bef_name.cc
Labels: ready to pull, cla: yes, windows

#74 Updates to get some of the unit tests within `backends/gpu/cpp_tests` working on the ROCm platform
  backends/gpu/BUILD
  backends/gpu/cpp_tests/BUILD
  backends/gpu/cpp_tests/instantiate_suite.cc
  backends/gpu/cpp_tests/wrapper/fft_wrapper_test.cc
  backends/gpu/cpp_tests/wrapper/runtime_wrapper_test.cc
  backends/gpu/include/tfrt/gpu/wrapper/cufft_wrapper.h
  backends/gpu/include/tfrt/gpu/wrapper/fft_wrapper.h
  backends/gpu/include/tfrt/gpu/wrapper/hip_forwards.h
  backends/gpu/include/tfrt/gpu/wrapper/hip_stub.h
  backends/gpu/include/tfrt/gpu/wrapper/hip_wrapper.h
  backends/gpu/include/tfrt/gpu/wrapper/hipfft_stub.h
  backends/gpu/include/tfrt/gpu/wrapper/hipfft_wrapper.h
  backends/gpu/include/tfrt/gpu/wrapper/rocfft_wrapper.h
  backends/gpu/include/tfrt/gpu/wrapper/rocsolver_stub.h
  backends/gpu/include/tfrt/gpu/wrapper/rocsolver_wrapper.h
  backends/gpu/lib/wrapper/cufft_wrapper.cc
  backends/gpu/lib/wrapper/fft_wrapper.cc
  backends/gpu/lib/wrapper/hip_wrapper.cc
  backends/gpu/lib/wrapper/hipfft_stub.cc
  backends/gpu/lib/wrapper/hipfft_wrapper.cc
  backends/gpu/lib/wrapper/miopen_stub.cc
  backends/gpu/lib/wrapper/rocfft_wrapper.cc
  backends/gpu/lib/wrapper/rocsolver_stub.cc
  backends/gpu/lib/wrapper/rocsolver_wrapper.cc
  backends/gpu/lib/wrapper/solver_wrapper.cc
  backends/gpu/tools/stub_codegen/cublas.json
  backends/gpu/tools/stub_codegen/cuda.json
  backends/gpu/tools/stub_codegen/cudart.json
  backends/gpu/tools/stub_codegen/cudnn.json
  backends/gpu/tools/stub_codegen/cufft.json
  backends/gpu/tools/stub_codegen/cusolverdn.json
  backends/gpu/tools/stub_codegen/generate.sh
  backends/gpu/tools/stub_codegen/header_codegen.py
  backends/gpu/tools/stub_codegen/hip.json
  backends/gpu/tools/stub_codegen/hipfft.json
  backends/gpu/tools/stub_codegen/miopen.json
  backends/gpu/tools/stub_codegen/rocblas.json
  backends/gpu/tools/stub_codegen/rocfft.json
  backends/gpu/tools/stub_codegen/rocsolver.json
  third_party/hip/hip_stub.cc.inc
  third_party/hip/hip_stub.h.inc
  third_party/hip/hipfft_stub.cc.inc
  third_party/hip/hipfft_stub.h.inc
  third_party/hip/miopen_stub.cc.inc
  third_party/hip/miopen_stub.h.inc
  third_party/hip/rocblas_stub.cc.inc
  third_party/hip/rocblas_stub.h.inc
  third_party/hip/rocfft_stub.cc.inc
  third_party/hip/rocfft_stub.h.inc
  third_party/hip/rocsolver_stub.cc.inc
  third_party/hip/rocsolver_stub.h.inc
Labels: cla: yes

#75 Fixes for misc Windows build issues and warnings
  cpp_tests/host_context/sync_kernel_test.cc
  cpp_tests/support/thread_local_test.cc
  include/tfrt/dtype/dtype.h
  include/tfrt/host_context/async_value.h
  include/tfrt/support/aligned_buffer.h
  lib/support/error_util.cc
Labels: cla: yes, windows

#78 rules_cuda: Updates the README instructions
  third_party/rules_cuda/README.md
Labels: ready to pull, cla: yes
